interface _data {
  id: {
    fromMe: boolean;
    remote: string;
    id: string;
    _serialized: string;
  },
  body: string;
  type: string;
  t: number;
  notifyName: string,
  from: string,
  to: string,
  self: string,
  ack: number,
  isNewMsg: true,
  star: boolean,
  kicNotified: boolean,
  recvFresh: boolean,
  isFromTemplate: boolean,
  pollInvalidated: boolean,
  isSentCagPollCreation: boolean,
  latestEditMsgKey: null,
  latestEditSenderTimestampMs: any,
  broadcast: boolean,
  mentionedJidList: any[],
  groupMentions: any[],
  isVcardOverMmsDocument: boolean,
  isForwarded: boolean,
  hasReaction: boolean,
  productHeaderImageRejected: boolean,
  lastPlaybackProgress: number,
  isDynamicReplyButtonsMsg: boolean,
  isMdHistoryMsg: boolean,
  stickerSentTs: number,
  isAvatar: boolean,
  lastUpdateFromServerTs: number,
  requiresDirectConnection: boolean,
  invokedBotWid: any,
  links: any[]
}

export interface IMessage {
  _data: _data;
  ack: number,
  hasMedia: boolean,
  body: string
  type: string,
  timestamp: number,
  from: string,
  to: string,
  author: string,
  deviceType: string,
  isForwarded: boolean,
  forwardingScore: number,
  isStatus: undefined,
  isStarred: boolean,
  broadcast: boolean,
  fromMe: boolean,
  hasQuotedMsg: boolean,
  duration: any,
  location: any,
  vCards: any[],
  inviteV4: any,
  mentionedIds: any[],
  orderId: any,
  token: any,
  isGif: boolean,
  isEphemeral: any,
  links: any[]
  getChat: any;
}